Sylius\Component\Core\Model\AdminUser:
    exclusion_policy: ALL
    xml_root_name: sylius_admin_user
    properties:
        firstName:
            expose: true
            type: string
            groups: [Detailed, Autocomplete]
        lastName:
            expose: true
            type: string
            groups: [Detailed, Autocomplete]
        localCode:
            expose: true
            type: string
            groups: [Detailed]
    virtual_properties:
        id:
            serialized_name: id
            type: integer
            groups: [Autocomplete]
            exp: "object.getId()"
        fullName:
            serialized_name: fullName
            type: string
            groups: [Autocomplete]
            exp: "object.getFirstName() ~ ' ' ~ object.getLastName()"
        descriptor:
            serialized_name: descriptor
            type: string
            groups: [Autocomplete]
            exp: "object.getFirstName() ~ ' ' ~ object.getLastName() ~ ' (' ~ object.getEmail() ~ ')'"
