eightlines_sylius_notification_plugin_notification:
    resource: |
        alias: eightlines_sylius_notification_plugin.notification
        section: admin
        templates: "@SyliusAdmin\\Crud"
        grid: eightlines_sylius_notification_plugin.notification
        permission: true
        redirect: update
        except: ['show']
        vars:
            all:
                templates:
                    form: "@EightLinesSyliusNotificationPlugin/Admin/Notification/_form.html.twig"
            index:
                icon: linkify
            update:
                templates:
                    form: "@EightLinesSyliusNotificationPlugin/Admin/Notification/_form.html.twig"
    type: sylius.resource
