sylius_grid:
    grids:
        cart_links_cart_link:
            driver:
                name: doctrine/orm
                options:
                    class: "%cart_links.model.cart_link.class%"
            sorting:
                code: asc
            fields:
                id:
                    type: string
                    label: sylius.ui.id
                    sortable: ~
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                
            actions:
                main:
                    create:
                        type: create
                        label: cart_links.ui.new_cart_link
                item:
                    update:
                        type: update
                    delete:
                        type: delete
