sylius_grid:
    grids:
        notification_rule:
            driver:
                name: doctrine/orm
                options:
                    class: "%notification.model.rule.class%"
                    repository:
                        method: createListQueryBuilder
                        arguments: ["%locale%"]
            sorting:
                code: asc
            limits: [10, 25, 50]
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: code
                translation.name:
                    type: string
                    label: sylius.ui.name
                    sortable: translation.name
                translation.slug:
                    type: string
                    label: sylius.ui.slug
                    sortable: translation.slug
                used:
                    type: string
                    label: sylius.ui.used
                    sortable: used
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, translation.name, translation.slug]
            actions:
                main:
                    create:
                        type: create
                        label: cart_links.ui.new_cart_link
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
