sylius_resource:
    resources:
        cart_links.cart_link:
            classes:
                model: EightLines\SyliusCartLinksPlugin\Entity\CartLink
                interface: EightLines\SyliusCartLinksPlugin\Entity\CartLinkInterface
                form: EightLines\SyliusCartLinksPlugin\Form\Type\CartLinkType
            translation:
                classes:
                    model: EightLines\SyliusCartLinksPlugin\Entity\CartLinkTranslation
        cart_links.cart_link_action:
            classes:
                model: EightLines\SyliusCartLinksPlugin\Entity\CartLinkAction
                interface: EightLines\SyliusCartLinksPlugin\Entity\CartLinkActionInterface
        cart_links.cart_link_usage:
            classes:
                model: EightLines\SyliusCartLinksPlugin\Entity\CartLinkUsage
                interface: EightLines\SyliusCartLinksPlugin\Entity\CartLinkUsageInterface
