sylius_resource:
    resources:
        notification.condition:
            classes:
                model: EightLines\SyliusNotificationPlugin\Entity\NotificationRule
                interface: EightLines\SyliusNotificationPlugin\Entity\NotificationRuleInterface
        notification.message:
            classes:
                model: EightLines\SyliusNotificationPlugin\Entity\NotificationRule
                interface: EightLines\SyliusNotificationPlugin\Entity\NotificationRuleInterface
            translation:
                classes:
                    model: EightLines\SyliusNotificationPlugin\Entity\NotificationMessageTranslation
        notification.rule:
            classes:
                model: EightLines\SyliusNotificationPlugin\Entity\NotificationRule
                interface: EightLines\SyliusNotificationPlugin\Entity\NotificationRuleInterface
