sylius_promotion:
    resources:
        promotion:
            classes:
                repository: EightLines\SyliusCartLinksPlugin\Repository\Sylius\PromotionRepository
        promotion_coupon:
            classes:
                repository: EightLines\SyliusCartLinksPlugin\Repository\Sylius\PromotionCouponRepository
